# Generated by Django 2.1.2 on 2018-10-29 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0003_auto_20181029_0141'),
    ]

    operations = [
        migrations.CreateModel(
            name='Perro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(upload_to='')),
                ('nombre', models.CharField(max_length=100)),
                ('raza', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=150)),
            ],
        ),
        migrations.RenameField(
            model_name='persona',
            old_name='nombre',
            new_name='nombreC',
        ),
    ]
