# Generated by Django 2.1.2 on 2018-10-29 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0004_auto_20181029_1449'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='contrasenia',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
