# Generated by Django 2.1.2 on 2018-10-30 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0006_auto_20181029_2249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perro',
            name='foto',
            field=models.ImageField(upload_to='media/fotos/'),
        ),
    ]
