# Generated by Django 2.1.2 on 2018-10-30 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0007_auto_20181029_2319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perro',
            name='foto',
            field=models.ImageField(upload_to='fotos/'),
        ),
    ]
