# Generated by Django 2.1.2 on 2018-10-30 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0008_auto_20181029_2323'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='pregunta',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
